name: Terraform Infra Deploy

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # Not used for STS, but silences the warning
      contents: read   
    outputs:
      ec2_ip: ${{ steps.output.outputs.ec2_ip }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials (AWS Academy STS)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${ { secrets.AWS_ACCESS_KEY_ID } }
          aws-secret-access-key: ${ { secrets.AWS_SECRET_ACCESS_KEY } }
          aws-session-token: ${ { secrets.AWS_SESSION_TOKEN } }  # Obligatorio para STS
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
      
      - name: Output EC2 IP
        id: output
        run: |
          echo "ec2_ip=$(terraform output -raw ec2_public_ip)" >> $GITHUB_OUTPUT