name: Terraform Infra Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:
    outputs:
      ags_name:
        description: "AGS Name"
        value: ${{ jobs.terraform.outputs.ags_name }}
      db_endpoint: 
        description: "DB Endpoint"
        value: ${{ jobs.terraform.outputs.db_endpoint }}
      alb_dns:
        description: "ALB DNS"
        value: ${{ jobs.terraform.outputs.alb_dns }}


jobs:
  terraform:
    environment: prod
    runs-on: ubuntu-latest

    outputs:
      db_endpoint: ${{ steps.output.outputs.db_endpoint }}
      alb_dns: ${{ steps.output.outputs.alb_dns }}
      ags_name: ${{ steps.output.outputs.ags_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials (AWS Academy STS)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

          

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: ./deploy-backend.sh
      
      - name: Output EC2 IP and DB Endpoint
        id: output
        run: |
          echo "db_endpoint=$(terraform output -raw db_endpoint)" >> $GITHUB_OUTPUT
          echo "alb_dns=$(terraform output -raw alb_dns)" >> $GITHUB_OUTPUT
          echo "ags_name=$(terraform output -raw ags_name)" >> $GITHUB_OUTPUT