name: Terraform Infra Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:
    outputs:
      ec2_ip:
        description: "EC2 IP"
        value: ${{ jobs.terraform.outputs.ec2_ip }}
      db_endpoint: 
        description: "DB Endpoint"
        value: ${{ jobs.terraform.outputs.db_endpoint }}


jobs:
  terraform:
    environment: prod
    runs-on: ubuntu-latest

    outputs:
      ec2_ip: ${{ steps.output.outputs.ec2_ip }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials (AWS Academy STS)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

          

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
      
      - name: Output EC2 IP and DB Endpoint
        id: output
        run: |
          echo "ec2_ip=$(terraform output -raw ec2_public_ip)" >> $GITHUB_OUTPUT
          echo "db_endpoint=$(terraform output -raw db_endpoint)" >> $GITHUB_OUTPUT